[tool.poetry]
name = "learn-fasthtml"
version = "0.1.0"
description = ""
authors = ["Shawn (SourceTree) <shawn.xiao@agoda.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
python-fasthtml = "0.8.0"
fastapi = "^0.115.3"

[tool.poetry.group.dev.dependencies]
fastapi = "^0.115.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
